#!/usr/bin/env python3
"""
scripts/dev/sync_claude_assets.py
Generates the Claude Code subagents and skills from the Antigravity (agy) definitions, which stay the
single source of truth:

  .agents/agents/<name>/agent.md         -> .claude/agents/<name>.md
  .agents/skills/<skill>/SKILL.md        -> .claude/skills/<skill>/SKILL.md   (SKILLS below)

Mapping rules:
  * agy tools -> Claude tools (view_file->Read, grep_search->Grep, list_dir/find_by_name->Glob,
    search_web->WebSearch, read_url_content->WebFetch); send_message / invoke_subagent are dropped
    (a Claude subagent answers with its final response; only the parent launches subagents).
    Agents with commandExecutionPolicy "off" are read-only: they never get Bash/Edit/Write. Only agents in
    WRITE_AGENTS may hold write tools, and each of them gets its Claude PreToolUse guard (CLAUDE_AGENT_HOOKS)
    in the generated frontmatter (agy cannot scope hooks to one subagent; the project hooks still apply there).
  * model inherit|sonnet|opus|haiku is kept; agy-only keys (mainAgent, subagent, commandExecutionPolicy,
    inheritCustomizations, inheritMcp) are dropped.
  * descriptions are rewritten for Claude (Agent tool / subagent_type / --from-claude-subagent).
  * bodies are copied verbatim after a generated-file banner and a short "Claude Code runtime" note;
    the few Claude-specific skill steps are overridden here (SKILL_OVERRIDES), never by hand.

Usage (repo root):
  python3 scripts/dev/sync_claude_assets.py           # (re)generate
  python3 scripts/dev/sync_claude_assets.py --check   # exit 1 if the generated files are stale

Exit codes: 0 up to date / written, 1 stale (--check), 2 invalid source definitions.
"""

import argparse
import os
import re
import sys
import textwrap

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
AGY_AGENTS_DIR = os.path.join(".agents", "agents")
AGY_SKILLS_DIR = os.path.join(".agents", "skills")
CLAUDE_AGENTS_DIR = os.path.join(".claude", "agents")
CLAUDE_SKILLS_DIR = os.path.join(".claude", "skills")
GENERATOR = "scripts/dev/sync_claude_assets.py"
GENERATED_MARKER = "GENERATED by " + GENERATOR

# Repo skills mirrored for Claude Code (third-party skills under .agents/skills are gitignored and skipped)
SKILLS = ("market-radar", "trade-execution-planner", "pr-review", "issue-orchestrator")
EVALUATOR = "isolated_market_evaluator"

TOOL_MAP = {
    "view_file": "Read",
    "grep_search": "Grep",
    "list_dir": "Glob",
    "find_by_name": "Glob",
    "search_web": "WebSearch",
    "read_url_content": "WebFetch",
}
WRITE_TOOL_MAP = {
    "run_command": "Bash",
    "write_to_file": "Write",
    "replace_file_content": "Edit",
    "multi_replace_file_content": "Edit",
}
DROPPED_TOOLS = {"send_message", "invoke_subagent"}
CLAUDE_WRITE_TOOLS = {"Bash", "Write", "Edit"}
# Agents allowed to hold write tools. Each MUST have a Claude PreToolUse guard below (fail closed: if the guard
# cannot run, `|| exit 2` blocks the tool call).
WRITE_AGENTS = {"issue_fixer"}
CLAUDE_AGENT_HOOKS = {
    "issue_fixer": (
        "hooks:\n"
        "  PreToolUse:\n"
        "    - matcher: Bash|Edit|Write|MultiEdit|NotebookEdit|Read|Grep|Glob\n"
        "      hooks:\n"
        "        - type: command\n"
        "          command: 'python3 \"$CLAUDE_PROJECT_DIR\"/scripts/hooks/issue_fixer_guard.py || exit 2'"
    ),
}
# Agents that work in an issue worktree named in their task message rather than in the session's checkout
WORKTREE_AGENTS = {"issue_locator", "issue_fixer", "issue_auditor"}
REPO_PATHS_LINE = ("Relative paths (e.g. `logs/...`, `research/`, `docs/`) are relative to the repository root, "
                   "your working directory.")
WORKTREE_PATHS_LINE = ("Relative paths below (e.g. `logs/issue_work/...`, `tests/`) are relative to WORKTREE, the "
                       "issue worktree named in your task message,\n  not to your working directory: always use "
                       "absolute paths under WORKTREE.")
CLAUDE_MODELS = {"inherit", "sonnet", "opus", "haiku"}
AGY_ONLY_KEYS = {"mainAgent", "subagent", "commandExecutionPolicy", "inheritCustomizations", "inheritMcp"}
# agy vocabulary that must not survive in a generated description
AGY_TERMS_RE = re.compile(r"invoke_subagent|send_message|TypeName|conversationId|define_subagent|view_file")

DESCRIPTION_REWRITES = [
    (re.compile(r'invoke_subagent \(TypeName "([\w-]+)"\)'), r'the Agent tool (subagent_type "\1")'),
    (re.compile(r'(?:call )?invoke_subagent with\s+TypeName "([\w-]+)"'), r'call the Agent tool with subagent_type "\1"'),
    (re.compile(r"wait for its message"), "wait for its final response"),
    (re.compile(r"`python3 scripts/record_evaluation\.py --from-subagent <conversationId>`"),
     "`python3 scripts/record_evaluation.py --from-claude-subagent <agentId>`"),
    (re.compile(r"replies once with send_message containing"), "replies once, in its final response, with"),
    (re.compile(r"one parallel invoke_subagent call with the required"),
     "parallel Agent tool calls (one message) for the required"),
]

BODY_REWRITES = [
    ("`python3 scripts/record_evaluation.py --from-subagent <conversationId>`",
     "`python3 scripts/record_evaluation.py --from-claude-subagent <agentId>`"),
    (".agents/skills/", ".claude/skills/"),
]

# --------------------------------------------------------------------------------------------------
# Claude-specific skill steps. Each override replaces the text from `start` up to (not including) `end`
# in the source SKILL.md; the generator fails if a marker disappears, so source edits cannot silently
# desynchronize the Claude flow.
# --------------------------------------------------------------------------------------------------
SKILL_OVERRIDES = {
    "trade-execution-planner": [
        {
            "start": "2. **Invoke the evaluator:**",
            "end": "4. **Record the verdict:**",
            "text": (
                "2. **Invoke the evaluator:** call the Agent tool with `subagent_type: \"isolated_market_evaluator\"` "
                "(generated into `.claude/agents/isolated_market_evaluator.md` from "
                "`.agents/agents/isolated_market_evaluator/agent.md`) in the foreground (`run_in_background: false` "
                "when the parameter exists). In the prompt, ask it to evaluate `logs/primed_brief.json` for the target "
                "environment; do not paraphrase the numbers yourself. Never substitute a general-purpose agent and "
                "never evaluate the brief yourself: the recorder only accepts transcripts whose agent type is "
                "`isolated_market_evaluator`.\n"
                "3. **Wait for its final response** containing the Master Dossier and its `<dossier_json>` block. "
                "Keep the subagent `agentId` reported in the Agent tool result (it looks like `a` + 16 hex digits).\n"
            ),
        },
    ],
    "pr-review": [
        {
            "start": "The review runs in the CURRENT session.",
            "end": "| Reviewer id (verdict header)",
            "text": (
                "The review runs in the CURRENT session. Each domain reviewer is a read-only Claude Code subagent\n"
                "(`.claude/agents/<reviewer>_reviewer.md`, generated from `.agents/agents/<reviewer>_reviewer/agent.md`)\n"
                "with a clean context; you orchestrate, they audit.\n\n"
            ),
        },
        {
            "start": "| Reviewer id (verdict header) | Subagent TypeName | Domain |",
            "end": "|---|---|---|",
            "text": "| Reviewer id (verdict header) | Agent `subagent_type` | Domain |\n",
        },
        {
            "start": "4. **Invoke all required reviewers in ONE `invoke_subagent` call**",
            "end": "5. **Assemble**",
            "text": (
                "4. **Launch all required reviewers in ONE message**: one Agent tool call per id in\n"
                "   `required_reviewers` (manifest order), so they run in parallel, each with\n"
                "   `subagent_type: \"<reviewer_details[id].agent>\"`, `description: \"<id> PR review\"` and this prompt:\n"
                "   \"Review PR #<n> (<base_ref>...<head_sha>) for the <id> domain only. Read logs/pr_review/index.md "
                "(your assigned files are under 'Assigned to `<id>`'), logs/pr_manifest.json and the patches in "
                "logs/pr_review/files/. Your final response must contain only your '### Verdict: <id>' section.\"\n"
                "   Note the `agentId` each Agent result reports, with its reviewer id. If the reviewers run in the\n"
                "   background, end your turn and wait for their completion notifications; do not poll and do not\n"
                "   relaunch running reviewers. Never review a domain yourself or with a general-purpose agent:\n"
                "   the assembler only accepts transcripts whose agent type is `<id>_reviewer`.\n"
            ),
        },
        {
            "start": "   `python3 scripts/ci/assemble_review.py --pr <n> --from-subagent <id>=<conversationId> ...`",
            "end": "\n",
            "text": "   `python3 scripts/ci/assemble_review.py --pr <n> --from-claude-subagent <id>=<agentId> ...`",
        },
        {
            "start": "Re-invoke ONLY those reviewers once",
            "end": "If still incomplete",
            "text": ("Re-launch ONLY those reviewers once (their Agent calls in\n"
                     "     one message), then re-run step 5 with all agent ids. "),
        },
    ],
}

AGENT_NOTE = """<claude_code_runtime>
You are running as a Claude Code subagent. The instructions below were written for Google Antigravity
(agy); apply them with this mapping:
- Tools: `view_file` = Read, `grep_search` = Grep, `list_dir` = Glob, `search_web` = WebSearch,
  `read_url_content` = WebFetch{write_map}. Use only the tools you were given{read_only}.
- `send_message` does not exist here: {delivery}
- {paths_line}
</claude_code_runtime>
"""

EVALUATOR_DELIVERY = (
    "deliver the complete Master Dossier, including its single `<dossier_json>` block,\n"
    "  as your final response (the last message you write), exactly once. The parent records it with\n"
    "  `python3 scripts/record_evaluation.py --from-claude-subagent <agentId>`, which reads the block from your\n"
    "  transcript and verifies that you ran as `isolated_market_evaluator`. The `## Precondition Checklist` and the\n"
    "  `<dossier_json>` block must be in the same final text block of your final response; a checklist written in\n"
    "  an earlier message is not read and an APPROVED dossier is then refused in PROD."
)
REVIEWER_DELIVERY = (
    "reply once, as your final response (the last message you write), with only your\n"
    "  `### Verdict: {rid}` section. The parent copies it verbatim with\n"
    "  `python3 scripts/ci/assemble_review.py --from-claude-subagent {rid}=<agentId>`, which verifies that you\n"
    "  ran as `{name}`."
)
GENERIC_DELIVERY = "deliver your final report as your final response (the last message you write)."

SKILL_NOTE = """> **Claude Code runtime.** Subagents are launched with the Agent tool (`subagent_type: "<name>"`, defined in
> `.claude/agents/`); a subagent's final response comes back to you, together with its `agentId`. Where the
> agy wording says `invoke_subagent` use the Agent tool, `conversationId` means the Claude Code `agentId`, and
> `view_file` means Read. Run the scripts from the repo root with Bash.
> Load sibling skills (e.g. `market-radar`) with the Skill tool; do not grep or Read their `SKILL.md`.
"""


class SourceError(Exception):
    pass


# --------------------------------------------------------------------------------------------------
# Frontmatter
# --------------------------------------------------------------------------------------------------
def split_frontmatter(text: str, source: str) -> tuple:
    text = text.replace("\r\n", "\n")
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise SourceError(f"{source}: missing YAML frontmatter")
    try:
        end = next(i for i in range(1, len(lines)) if lines[i].strip() == "---")
    except StopIteration:
        raise SourceError(f"{source}: unterminated YAML frontmatter")
    return lines[1:end], "\n".join(lines[end + 1:]).lstrip("\n")


def _scalar(value: str):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in ("'", '"'):
        return value[1:-1]
    if value == "true":
        return True
    if value == "false":
        return False
    return value


def parse_frontmatter(lines: list, source: str) -> dict:
    """Minimal YAML subset used by the agy definitions: scalars, folded/literal blocks and '- item' lists."""
    data, key, mode = {}, None, None
    for raw in lines:
        if not raw.strip():
            if mode == "block" and isinstance(data.get(key), str) and data[key]:
                data[key] += "\n"
            continue
        if raw.startswith((" ", "\t")):
            if key is None:
                raise SourceError(f"{source}: indented line outside a key: {raw!r}")
            stripped = raw.strip()
            if stripped.startswith("- ") and mode in ("list", None):
                data[key] = (data[key] if isinstance(data[key], list) else []) + [_scalar(stripped[2:])]
                mode = "list"
            else:
                current = data[key] if isinstance(data[key], str) else ""
                sep = "" if not current or current.endswith("\n") else " "
                data[key] = current + sep + stripped
                mode = "block"
            continue
        if ":" not in raw:
            raise SourceError(f"{source}: unsupported frontmatter line {raw!r}")
        key, _, value = raw.partition(":")
        key, value = key.strip(), value.strip()
        if value in (">-", ">", "|", "|-"):
            data[key], mode = "", "block"
        elif value == "":
            data[key], mode = [], None
        else:
            data[key], mode = _scalar(value), "scalar"
    for k, v in data.items():
        if isinstance(v, str):
            data[k] = " ".join(v.split())
    return data


def yaml_folded(key: str, text: str) -> str:
    wrapped = textwrap.wrap(" ".join(text.split()), width=100, break_long_words=False, break_on_hyphens=False)
    return f"{key}: >-\n" + "\n".join("  " + line for line in wrapped)


def rewrite_description(desc: str, source: str) -> str:
    for pattern, repl in DESCRIPTION_REWRITES:
        desc = pattern.sub(repl, desc)
    leftover = AGY_TERMS_RE.findall(desc)
    if leftover:
        raise SourceError(f"{source}: description still uses agy terms {sorted(set(leftover))}; "
                          f"add a rewrite rule to {GENERATOR}")
    return desc


def banner(source_rel: str) -> str:
    return (f"<!-- {GENERATED_MARKER} from {source_rel}. Do not edit: change the source and re-run "
            f"`python3 {GENERATOR}`. -->\n")


# --------------------------------------------------------------------------------------------------
# Agents
# --------------------------------------------------------------------------------------------------
def map_tools(tools: list, read_only: bool, source: str) -> list:
    out = []
    for tool in tools or []:
        if tool in DROPPED_TOOLS:
            continue
        if tool in TOOL_MAP:
            mapped = TOOL_MAP[tool]
        elif tool in WRITE_TOOL_MAP:
            if read_only:
                raise SourceError(f"{source}: read-only agent (commandExecutionPolicy off) lists write tool '{tool}'")
            mapped = WRITE_TOOL_MAP[tool]
        else:
            raise SourceError(f"{source}: unknown agy tool '{tool}'; add it to TOOL_MAP in {GENERATOR}")
        if mapped not in out:
            out.append(mapped)
    return out


def agent_delivery(name: str) -> str:
    if name == EVALUATOR:
        return EVALUATOR_DELIVERY
    if name.endswith("_reviewer"):
        return REVIEWER_DELIVERY.format(rid=name[: -len("_reviewer")], name=name)
    return GENERIC_DELIVERY


def render_agent(source_rel: str, text: str) -> tuple:
    fm_lines, body = split_frontmatter(text, source_rel)
    fm = parse_frontmatter(fm_lines, source_rel)
    name = fm.get("name")
    folder = os.path.basename(os.path.dirname(source_rel))
    if not name or name != folder:
        raise SourceError(f"{source_rel}: frontmatter name '{name}' must match its folder '{folder}'")
    if not fm.get("description"):
        raise SourceError(f"{source_rel}: missing description")
    unknown = set(fm) - {"name", "description", "tools", "model"} - AGY_ONLY_KEYS
    if unknown:
        raise SourceError(f"{source_rel}: unsupported frontmatter keys {sorted(unknown)}")

    read_only = str(fm.get("commandExecutionPolicy", "")).lower() == "off"
    tools = map_tools(fm.get("tools") if isinstance(fm.get("tools"), list) else [], read_only, source_rel)
    model = str(fm.get("model", "")).strip()

    if set(tools) & CLAUDE_WRITE_TOOLS:
        if name not in WRITE_AGENTS:
            raise SourceError(f"{source_rel}: only {sorted(WRITE_AGENTS)} may hold write tools "
                              f"({sorted(set(tools) & CLAUDE_WRITE_TOOLS)}); add it to WRITE_AGENTS with a guard")
        if not CLAUDE_AGENT_HOOKS.get(name):
            raise SourceError(f"{source_rel}: write agent '{name}' has no PreToolUse guard in CLAUDE_AGENT_HOOKS")

    out = ["---", f"name: {name}", yaml_folded("description", rewrite_description(fm["description"], source_rel))]
    if tools:
        out.append("tools: " + ", ".join(tools))
    if model in CLAUDE_MODELS:
        out.append(f"model: {model}")
    if name in CLAUDE_AGENT_HOOKS:
        out.append(CLAUDE_AGENT_HOOKS[name])
    out.append("---")
    note = AGENT_NOTE.format(
        write_map=(", `run_command` = Bash, `write_to_file` = Write,\n  `replace_file_content` / "
                   "`multi_replace_file_content` = Edit" if set(tools) & CLAUDE_WRITE_TOOLS else ""),
        read_only=" (read-only: you cannot run commands or edit files)" if read_only else "",
        delivery=agent_delivery(name),
        paths_line=WORKTREE_PATHS_LINE if name in WORKTREE_AGENTS else REPO_PATHS_LINE,
    )
    content = "\n".join(out) + "\n\n" + banner(source_rel) + "\n" + note + "\n" + body.rstrip("\n") + "\n"
    return os.path.join(CLAUDE_AGENTS_DIR, f"{name}.md"), content


# --------------------------------------------------------------------------------------------------
# Skills
# --------------------------------------------------------------------------------------------------
def apply_overrides(body: str, overrides: list, source: str) -> str:
    for ov in overrides:
        start = body.find(ov["start"])
        if start < 0:
            raise SourceError(f"{source}: override start marker not found: {ov['start']!r}")
        end = body.find(ov["end"], start + len(ov["start"]))
        if end < 0:
            raise SourceError(f"{source}: override end marker not found after {ov['start']!r}: {ov['end']!r}")
        body = body[:start] + ov["text"] + body[end:]
    return body


def render_skill(skill: str, source_rel: str, text: str) -> tuple:
    fm_lines, body = split_frontmatter(text, source_rel)
    fm = parse_frontmatter(fm_lines, source_rel)
    if fm.get("name") != skill:
        raise SourceError(f"{source_rel}: frontmatter name '{fm.get('name')}' must be '{skill}'")
    if not fm.get("description"):
        raise SourceError(f"{source_rel}: missing description")
    body = apply_overrides(body, SKILL_OVERRIDES.get(skill, []), source_rel)
    for old, new in BODY_REWRITES:
        body = body.replace(old, new)
    leftover = re.findall(r"invoke_subagent|send_message|TypeName|conversationId", body)
    if leftover:
        raise SourceError(f"{source_rel}: Claude skill body still uses agy terms {sorted(set(leftover))}; "
                          f"add an override to SKILL_OVERRIDES in {GENERATOR}")
    out = ["---", f"name: {skill}", yaml_folded("description", rewrite_description(fm["description"], source_rel)),
           "---"]
    content = "\n".join(out) + "\n\n" + banner(source_rel) + "\n" + SKILL_NOTE + "\n" + body.rstrip("\n") + "\n"
    return os.path.join(CLAUDE_SKILLS_DIR, skill, "SKILL.md"), content


# --------------------------------------------------------------------------------------------------
# Driver
# --------------------------------------------------------------------------------------------------
def _read(root: str, rel: str) -> str:
    with open(os.path.join(root, rel), "r", encoding="utf-8") as f:
        return f.read()


def build_expected(root: str = REPO_ROOT) -> dict:
    """Returns {repo-relative path (POSIX): content} for every generated file."""
    expected = {}
    agents_root = os.path.join(root, AGY_AGENTS_DIR)
    for name in sorted(os.listdir(agents_root)):
        src = os.path.join(AGY_AGENTS_DIR, name, "agent.md")
        if not os.path.isfile(os.path.join(root, src)):
            continue
        rel_src = src.replace(os.sep, "/")
        dest, content = render_agent(rel_src, _read(root, src))
        expected[dest.replace(os.sep, "/")] = content
    for skill in SKILLS:
        src = os.path.join(AGY_SKILLS_DIR, skill, "SKILL.md")
        if not os.path.isfile(os.path.join(root, src)):
            raise SourceError(f"missing skill source {src}")
        dest, content = render_skill(skill, src.replace(os.sep, "/"), _read(root, src))
        expected[dest.replace(os.sep, "/")] = content
    return expected


def existing_generated(root: str = REPO_ROOT) -> set:
    """Generated files currently on disk (identified by the banner), repo-relative POSIX paths."""
    found = set()
    candidates = []
    agents_dir = os.path.join(root, CLAUDE_AGENTS_DIR)
    if os.path.isdir(agents_dir):
        candidates += [os.path.join(CLAUDE_AGENTS_DIR, f) for f in os.listdir(agents_dir) if f.endswith(".md")]
    skills_dir = os.path.join(root, CLAUDE_SKILLS_DIR)
    if os.path.isdir(skills_dir):
        candidates += [os.path.join(CLAUDE_SKILLS_DIR, d, "SKILL.md") for d in os.listdir(skills_dir)]
    for rel in candidates:
        path = os.path.join(root, rel)
        if os.path.isfile(path):
            try:
                if GENERATED_MARKER in _read(root, rel):
                    found.add(rel.replace(os.sep, "/"))
            except (OSError, UnicodeDecodeError):
                continue
    return found


def check(root: str = REPO_ROOT) -> list:
    """Returns a list of problems (empty when the generated files are up to date)."""
    problems = []
    expected = build_expected(root)
    for rel, content in expected.items():
        path = os.path.join(root, rel)
        if not os.path.isfile(path):
            problems.append(f"missing: {rel}")
            continue
        with open(path, "r", encoding="utf-8") as f:
            current = f.read().replace("\r\n", "\n")
        if current != content:
            problems.append(f"stale: {rel}")
    for rel in sorted(existing_generated(root) - set(expected)):
        problems.append(f"orphan generated file (source removed): {rel}")
    return problems


def write(root: str = REPO_ROOT) -> list:
    expected = build_expected(root)
    changed = []
    for rel, content in expected.items():
        path = os.path.join(root, rel)
        current = None
        if os.path.isfile(path):
            with open(path, "r", encoding="utf-8") as f:
                current = f.read().replace("\r\n", "\n")
        if current != content:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(content)
            changed.append(rel)
    for rel in sorted(existing_generated(root) - set(expected)):
        os.remove(os.path.join(root, rel))
        changed.append(f"{rel} (removed)")
    return changed


def main(argv: list = None) -> int:
    parser = argparse.ArgumentParser(description="Generate Claude Code agents/skills from the agy definitions.")
    parser.add_argument("--check", action="store_true", help="Exit 1 if the generated files are stale.")
    parser.add_argument("--root", default=REPO_ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    try:
        if args.check:
            problems = check(args.root)
            for p in problems:
                print(p)
            if problems:
                print(f"Claude Code assets are out of date. Run: python3 {GENERATOR}")
                return 1
            print("Claude Code assets are up to date.")
            return 0
        changed = write(args.root)
        for rel in changed:
            print(f"updated: {rel}")
        print("Claude Code assets are up to date." if not changed else f"{len(changed)} file(s) updated.")
        return 0
    except SourceError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
