#!/usr/bin/env python3
"""
issue_fixer_guard.py - PreToolUse hook scoped to the `issue_fixer` subagent. Claude Code only: it runs as a
frontmatter hook generated by scripts/dev/sync_claude_assets.py (matcher Bash|Edit|Write|MultiEdit|NotebookEdit);
agy cannot scope hooks to one subagent, so under agy no guard runs. The project hooks (pre_trade_guard.py) still
run as well and stay the hard boundary for trading actions.

This is a confinement policy, not a sandbox: a denylist of programs plus path, quoting and binding rules. The
fixer edits code and runs tests inside ONE linked issue worktree; it never commits, pushes, calls GitHub or the
network, installs packages, runs desk runtime scripts or touches the main checkout (where the running hooks,
this guard included, live).

  * Edit / Write / MultiEdit / NotebookEdit: the absolute target must be inside a linked worktree of this
    repository (never the main checkout), and never under .git/, .claude/, .agents/hooks.json or logs/ (except
    logs/issue_work/). Never the running guard file (os.path.realpath(__file__), which matters when a session
    runs from a worktree) nor a worktree's logs/issue_work/guard_heartbeat.json or fixer_binding.json.
  * Bash:
      - the command must start with `cd <absolute path of a linked worktree>`: that is the issue worktree. Later
        `cd`s must stay inside it, at the top level (no subshell, pipeline or `||`), and a conditional `cd`
        (`... && cd X`) may not be followed by `;`, `&` or `||`, so the tracked directory is the real one;
      - every segment (split on ; && || | & newlines and subshell parentheses; a `#` comment only at a word
        start, a carriage return is an ordinary character, as in bash) is checked; wrappers (env, timeout, nice,
        nohup, time, command, stdbuf, xargs) are unwrapped; xargs may feed only XARGS_PROGRAMS (read-only, its
        arguments come from stdin), never another wrapper; `VAR=value` prefixes and `env VAR=value` only for
        ENV_ALLOWED names, and never as a segment of their own;
      - command and process substitution, heredocs, `$` expansions outside single quotes (except `$?` in echo /
        printf text), `~user` / `~+` / `~-`, unquoted brace expansion and shell compound commands (if, for,
        while, { }) are denied;
      - paths: write targets (redirections; cp mv tee sed -i rm touch mkdir dd of= install truncate chmod;
        sort -o) must resolve inside the issue worktree (with the edit-tool rules above), /dev/null or the temp
        dir; other path-like arguments too, or under the Python prefix for read-only programs (stdlib and
        site-packages). Unquoted globs are expanded and every match is checked, and so are the directory part
        before the first glob and, with no match, the literal word; a glob as a write target or an argument of
        a program the guard does not know (it may write) is denied. The main checkout, the home directory and
        every other issue worktree are off limits;
      - git: read-only subcommands only; python: only `-m unittest|compileall|py_compile|pytest`, test files
        under tests/ and scripts/dev/sync_claude_assets.py of the issue worktree (resolved, so `..` and symlinks
        cannot point elsewhere);
      - programs that can execute other programs (find -exec, awk, sed's e/w commands, make, editors, launchers
        such as setsid / flock / taskset, tar / zip, other interpreters and shells), shell builtins that change
        the environment (export, set, alias...), network tools, package managers, GitHub CLI and privilege
        escalation are denied.
  * Binding: `issue_workspace.py init` writes <worktree>/logs/issue_work/fixer_binding.json. The first allowed
    call that carries a session_id claims it; calls from another session are then denied in that worktree. A
    worktree without the marker (created before it existed) is accepted unbound: a documented legacy limit.
  * Heartbeat: main() writes <worktree>/logs/issue_work/guard_heartbeat.json after every decision (best effort,
    never changes the decision); `issue_workspace.py check-guard` lets the orchestrator verify the guard ran.

Limits: tests the fixer writes are code and run with the test runner; the auditor and the PR reviewers review that
code before merge. The guard prevents direct misuse; it is not a sandbox.

Contract (Claude Code hooks): hook JSON on stdin; exit 0 allows, exit 2 denies (reason on stderr). Malformed input
or an unresolvable repository is denied (fail closed).
"""

import glob
import json
import os
import re
import shlex
import subprocess
import sys
import tempfile
import time

EDIT_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}
GIT_READ_SUBCOMMANDS = {
    "diff", "status", "log", "show", "grep", "ls-files", "blame", "rev-parse", "describe", "shortlog",
    "cat-file", "ls-tree", "merge-base", "diff-tree", "name-rev", "rev-list", "whatchanged",
}
GIT_DENIED_ARGS = ("--ext-diff", "-O", "--open-files-in-pager", "--output")
PYTHON_MODULES = {"unittest", "compileall", "py_compile", "pytest"}
PYTHON_FLAGS_NO_ARG = set("bBdEhiIOqsSuvVxR")
PYTHON_FLAGS_WITH_ARG = {"-W", "-X"}
# Matched against the script's worktree-relative path after os.path.realpath
PYTHON_SCRIPT_RE = re.compile(r"^(tests/.+\.py|scripts/dev/sync_claude_assets\.py)$")
PYTHON_NAME_RE = re.compile(r"^(python|python3(\.\d+)?|py)$")

DENIED_PROGRAMS = {
    # GitHub / network / remote access
    "gh", "curl", "wget", "ssh", "scp", "sftp", "rsync", "nc", "ncat", "netcat", "telnet", "ftp", "socat",
    # package managers and build tools that run arbitrary recipes
    "pip", "pip3", "pipx", "npm", "npx", "yarn", "pnpm", "apt", "apt-get", "brew", "conda", "uv", "poetry",
    "make", "gmake", "cmake",
    # privilege, containers, OS bridges and services
    "sudo", "su", "doas", "docker", "podman", "kubectl", "wsl", "wsl.exe", "powershell", "powershell.exe",
    "pwsh", "cmd", "cmd.exe", "crontab", "systemctl", "service", "at", "pkill", "killall", "open", "xdg-open",
    # shells, indirection, interpreters and programs that execute other programs
    "eval", "exec", "source", ".", "bash", "sh", "zsh", "dash", "ksh", "fish", "perl", "ruby", "node", "deno",
    "php", "lua", "osascript", "awk", "gawk", "mawk", "nawk", "busybox", "watch", "parallel", "script",
    "expect", "tclsh", "strace", "gdb", "vi", "vim", "nvim", "emacs", "ed", "ex", "nano",
    # launchers that run their arguments, archivers with exec hooks, patch and links
    "setsid", "flock", "ionice", "chrt", "taskset", "unshare", "nsenter", "chroot", "runuser", "sg", "faketime",
    "tar", "zip", "unzip", "patch", "ln",
    # builtins that change the shell environment or the directory stack
    "export", "declare", "typeset", "alias", "set", "trap", "shopt", "builtin", "pushd", "popd",
}
SHELL_KEYWORDS = {"if", "then", "elif", "else", "fi", "for", "while", "until", "do", "done", "case", "esac",
                  "select", "function", "{", "}", "!", "[[", "]]", "coproc"}
# The only variables a `VAR=value` prefix or `env VAR=value` may set
ENV_ALLOWED = {"PYTHONDONTWRITEBYTECODE", "PYTHONUNBUFFERED", "PYTHONHASHSEED", "PYTHONIOENCODING", "LC_ALL",
               "LANG", "TZ", "CI", "NO_COLOR", "TERM", "COLUMNS"}
WRAPPERS = {"env", "timeout", "nice", "nohup", "time", "command", "stdbuf", "xargs"}
# The only programs xargs may run: its arguments come from stdin, unseen by the guard, so only read-only programs
# without write or exec options
XARGS_PROGRAMS = {"grep", "egrep", "fgrep", "cat", "head", "tail", "wc", "ls", "stat", "md5sum", "sha256sum"}
WRAPPER_FLAGS_WITH_ARG = {
    "timeout": {"-s", "--signal", "-k", "--kill-after"},
    "nice": {"-n", "--adjustment"},
    "stdbuf": {"-i", "-o", "-e"},
    "xargs": {"-n", "-I", "-L", "-P", "-d", "-s", "-E", "-a", "--max-args", "--replace", "--max-lines",
              "--max-procs", "--delimiter", "--arg-file"},
    "env": {"-u", "--unset"},
}
FIND_EXEC_ARGS = {"-exec", "-execdir", "-ok", "-okdir", "-fprint", "-fprint0", "-fprintf", "-fls", "-delete"}
# sed `e` (execute) / `w` `W` (write file) commands, with an optional address (1e, $e, /re/e, 1,5w), and the
# s///e and s///w flags
_SED_ADDR = r"(?:\d+|\$|/(?:[^/\\]|\\.)*/)"
SED_EXEC_RE = re.compile(
    r"(^|[;{}\n])\s*(?:" + _SED_ADDR + r"(?:\s*,\s*" + _SED_ADDR + r")?)?\s*!?\s*[eWw](\s|;|$)"
    r"|/[0-9gpIiMm]*[ew][0-9gpIiMm]*\s*($|[;}\s])"
)
RAW_DENY = [
    (re.compile(r"\$\("), "command substitution $(...)"),
    (re.compile(r"`"), "backtick command substitution"),
    (re.compile(r"[<>]\("), "process substitution"),
    (re.compile(r"<<"), "heredoc (use the Write/Edit tools to create files)"),
    (re.compile(r"CLAUDE_PROJECT_DIR"), "$CLAUDE_PROJECT_DIR (the main checkout is off limits)"),
]
OPERATORS = {";", "&&", "||", "|", "&", "|&", "(", ")", ";;"}
REDIRECTIONS = {"<", ">", ">>", "<>", ">&", "<&", "&>", "&>>", ">|"}
PUNCT_CHARS = ";&|()<>"
SHELL_BLANKS = " \t\n"  # bash's word separators; a carriage return is NOT one (shlex's default includes it)
# Longest first: a run of operator characters is split the way bash reads it (`&&>` = `&&` then `>`)
_PUNCT_TOKENS = sorted(OPERATORS | REDIRECTIONS, key=len, reverse=True)
LIST_SEPARATORS = {";", "&", "(", ")", ";;"}
ASSIGNMENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")
# Characters that start a parameter, arithmetic or command expansion right after `$`
EXPANSION_START = set("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_{([@*#?$!-")

# Path roles of program arguments
READ, WRITE, MAYBE_WRITE, SKIP = "read", "write", "maybe_write", "skip"
READ_PROGRAMS = {"cat", "head", "tail", "less", "more", "grep", "egrep", "fgrep", "rg", "find", "ls", "wc", "sed",
                 "diff", "cmp", "stat", "file", "sort", "uniq", "cut", "tr", "nl", "du", "md5sum", "sha256sum",
                 "git"}
WRITE_PROGRAMS = {"cp", "mv", "tee", "rm", "rmdir", "touch", "mkdir", "dd", "install", "truncate", "chmod"}
NO_PATH_PROGRAMS = {"echo", "printf"}
PATTERN_PROGRAMS = {"grep", "egrep", "fgrep", "rg", "sed"}  # first positional = pattern / script, unless -e/-f
SCRIPT_OPTS = {"-e", "-f", "--regexp", "--file", "--expression"}
_GREP_SHORT = "efmABCdD"
_GREP_LONG = {"--regexp", "--file", "--max-count", "--after-context", "--before-context", "--context", "--include",
              "--exclude", "--exclude-dir", "--label"}
_GREP_VALUES = {"-e": SKIP, "--regexp": SKIP, "--include": SKIP, "--exclude": SKIP, "--exclude-dir": SKIP,
                "--label": SKIP}
_TARGET_VALUES = {"-t": WRITE, "--target-directory": WRITE}
SHORT_VALUE_OPTS = {
    "grep": _GREP_SHORT, "egrep": _GREP_SHORT, "fgrep": _GREP_SHORT, "rg": "efgtTmABCjME", "sed": "efl",
    "cp": "tS", "mv": "tS", "install": "tmogS", "mkdir": "m", "touch": "dtr", "truncate": "sr", "head": "nc",
    "tail": "ncs", "sort": "kotST", "cut": "dfbc", "uniq": "fsw", "ls": "IwT", "du": "dBtX", "diff": "xXIFL",
}
LONG_VALUE_OPTS = {
    "grep": _GREP_LONG, "egrep": _GREP_LONG, "fgrep": _GREP_LONG,
    "rg": {"--regexp", "--file", "--glob", "--iglob", "--type", "--type-not", "--max-count", "--after-context",
           "--before-context", "--context"},
    "sed": {"--expression", "--file", "--line-length"},
    "cp": {"--target-directory", "--suffix"}, "mv": {"--target-directory", "--suffix"},
    "install": {"--target-directory", "--mode", "--owner", "--group", "--suffix"},
    "sort": {"--key", "--output", "--field-separator", "--temporary-directory"},
    "cut": {"--delimiter", "--fields", "--bytes", "--characters"},
}
VALUE_ROLES = {
    "grep": _GREP_VALUES, "egrep": _GREP_VALUES, "fgrep": _GREP_VALUES,
    "rg": {"-e": SKIP, "--regexp": SKIP, "-g": SKIP, "--glob": SKIP, "--iglob": SKIP, "-t": SKIP, "--type": SKIP,
           "-T": SKIP, "--type-not": SKIP},
    "sed": {"-e": SKIP, "--expression": SKIP},
    "cp": _TARGET_VALUES, "mv": _TARGET_VALUES, "install": _TARGET_VALUES,
    "sort": {"-o": WRITE, "--output": WRITE, "-T": WRITE, "--temporary-directory": WRITE},
}

RUNNING_GUARD = os.path.realpath(__file__)
WORK_DIR = "logs/issue_work"
BINDING_FILE = "fixer_binding.json"
HEARTBEAT_FILE = "guard_heartbeat.json"
PROTECTED_WORK_FILES = {f"{WORK_DIR}/{BINDING_FILE}", f"{WORK_DIR}/{HEARTBEAT_FILE}"}
TEMP_ROOTS = sorted({os.path.realpath(tempfile.gettempdir()), os.path.realpath("/tmp")})
PYTHON_PREFIXES = sorted({os.path.realpath(p) for p in (sys.prefix, sys.base_prefix, sys.exec_prefix,
                                                        sys.base_exec_prefix)})
START_MESSAGE = "every command must start with `cd <absolute path of the issue worktree> && ...`"


class Denied(Exception):
    pass


class Confinement:
    """The main checkout (off limits) and the linked worktrees (where the fixer may work)."""

    def __init__(self, main_root: str, worktrees: list):
        self.main_root = os.path.realpath(main_root)
        self.worktrees = [os.path.realpath(w) for w in worktrees if os.path.realpath(w) != self.main_root]

    @classmethod
    def from_project_dir(cls, project_dir: str) -> "Confinement":
        common = subprocess.run(["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
                                cwd=project_dir, capture_output=True, text=True, timeout=10)
        if common.returncode != 0:
            raise Denied(f"cannot resolve the repository from {project_dir}")
        main_root = os.path.dirname(common.stdout.strip().rstrip("/"))
        listing = subprocess.run(["git", "worktree", "list", "--porcelain"], cwd=main_root,
                                 capture_output=True, text=True, timeout=10)
        if listing.returncode != 0:
            raise Denied("cannot list the repository worktrees")
        trees = [ln[len("worktree "):] for ln in listing.stdout.splitlines() if ln.startswith("worktree ")]
        return cls(main_root, trees)

    @staticmethod
    def _under(path: str, root: str) -> bool:
        return path == root or path.startswith(root.rstrip(os.sep) + os.sep)

    def in_main(self, path: str) -> bool:
        return self._under(os.path.realpath(path), self.main_root)

    def worktree_of(self, path: str) -> str:
        real = os.path.realpath(path)
        return next((w for w in self.worktrees if self._under(real, w)), "")


# --------------------------------------------------------------------------------------------------
# Edit tools (and Bash write targets inside the issue worktree)
# --------------------------------------------------------------------------------------------------
def _check_tree_write(shown: str, real: str, tree: str) -> None:
    """Rules for any write inside a worktree, whichever tool makes it."""
    if real == RUNNING_GUARD:
        raise Denied(f"{shown} is the running guard (off limits)")
    rel = os.path.relpath(real, tree).replace(os.sep, "/")
    if rel == ".":
        raise Denied(f"{shown}: the worktree root itself cannot be a write target")
    parts = rel.split("/")
    if ".git" in parts:
        raise Denied(f"{shown}: git internals are off limits")
    if parts[0] == ".claude":
        raise Denied(f"{shown}: .claude/ is generated or local configuration (edit .agents/ and run the generator)")
    if rel == ".agents/hooks.json":
        raise Denied(f"{shown}: hook configuration is off limits")
    if parts[0] == "logs" and (len(parts) < 3 or parts[1] != "issue_work"):
        raise Denied(f"{shown}: only logs/issue_work/ may be written under logs/")
    if rel in PROTECTED_WORK_FILES:
        raise Denied(f"{shown}: {parts[-1]} is written only by the guard and issue_workspace.py")


def check_edit_path(path, conf: Confinement) -> None:
    if not isinstance(path, str) or not path:
        raise Denied("missing file path")
    if not os.path.isabs(path):
        raise Denied(f"{path}: use an absolute path inside the issue worktree")
    tree = conf.worktree_of(path)
    if not tree or conf.in_main(path):
        raise Denied(f"{path} is outside the issue worktrees (the main checkout and other directories are off "
                     "limits)")
    _check_tree_write(path, os.path.realpath(path), tree)


# --------------------------------------------------------------------------------------------------
# Bash: parsing
# --------------------------------------------------------------------------------------------------
class Word:
    """A shell word as shlex returns it, plus one quoting flag per character: u (unquoted), d (inside double
    quotes), s (inside single quotes), e (backslash-escaped) or p (operator character)."""
    __slots__ = ("text", "flags")

    def __init__(self, text: str, flags: str):
        self.text, self.flags = text, flags

    def tail(self, start: int) -> "Word":
        return Word(self.text[start:], self.flags[start:])


class Segment:
    """One simple command: its words, its redirections ((operator, target Word)), its subshell depth and the
    operators met before it (since the previous segment) and after it."""

    def __init__(self, depth: int = 0):
        self.words, self.redirs, self.depth, self.ops_before, self.ops_after = [], [], depth, [], []

    @property
    def prev(self):
        return self.ops_before[-1] if self.ops_before else None

    @property
    def next(self):
        return self.ops_after[0] if self.ops_after else None


def _unquoted_newlines_to_separators(command: str) -> str:
    """What bash runs, as one line: unquoted newlines become ';' so every line is its own segment; line
    continuations (backslash-newline outside single quotes) are removed; backslash escapes are honoured (`\\"`
    opens no quote, `\\\\` before a newline is no continuation); a `#` comment is dropped up to the end of the
    line, but only where bash starts one: at a word start, i.e. after an unquoted, unescaped space, tab, newline or
    one of ;&|()<> (never after an escaped character). A carriage return is an ordinary word character, as in bash
    (`cd x<CR>` names the directory "x<CR>")."""
    out, quote, word_start, i, n = [], None, True, 0, len(command)
    while i < n:
        ch = command[i]
        if quote == "'":
            quote = None if ch == "'" else quote
            out.append(ch)
            i += 1
            continue
        if ch == "\\" and i + 1 < n:
            if command[i + 1] == "\n":
                i += 2
                continue
            out.append(command[i:i + 2])
            word_start = False
            i += 2
            continue
        if quote == '"':
            quote = None if ch == '"' else quote
        elif ch in ("'", '"'):
            quote = ch
        elif ch == "\n":
            ch = ";"
        elif ch == "#" and word_start:
            while i < n and command[i] != "\n":
                i += 1
            continue
        word_start = quote is None and ch in " \t" + PUNCT_CHARS
        out.append(ch)
        i += 1
    return "".join(out)


def _shlex_tokens(prepared: str) -> list:
    lexer = shlex.shlex(prepared, posix=True, punctuation_chars=PUNCT_CHARS)
    lexer.whitespace_split = True
    lexer.whitespace = SHELL_BLANKS
    lexer.commenters = ""
    try:
        return list(lexer)
    except ValueError as e:
        raise Denied(f"unparseable command ({e})")


def _scan_words(prepared: str) -> list:
    """Second, quote-aware pass over the same text: mirrors the shlex split above and records how each
    character was quoted. The caller checks that both passes agree."""
    words, text, flags, in_word = [], [], [], False
    i, n = 0, len(prepared)

    def flush():
        nonlocal text, flags, in_word
        if in_word:
            words.append(Word("".join(text), "".join(flags)))
        text, flags, in_word = [], [], False

    while i < n:
        c = prepared[i]
        if c in SHELL_BLANKS:
            flush()
            i += 1
        elif c in PUNCT_CHARS:
            flush()
            j = i
            while j < n and prepared[j] in PUNCT_CHARS:
                j += 1
            words.append(Word(prepared[i:j], "p" * (j - i)))
            i = j
        elif c == "'":
            j = prepared.find("'", i + 1)
            if j < 0:
                raise Denied("unparseable command (No closing quotation)")
            text.append(prepared[i + 1:j])
            flags.append("s" * (j - i - 1))
            in_word, i = True, j + 1
        elif c == '"':
            in_word, i = True, i + 1
            while True:
                if i >= n:
                    raise Denied("unparseable command (No closing quotation)")
                c = prepared[i]
                if c == '"':
                    i += 1
                    break
                if c == "\\" and i + 1 < n:
                    nxt = prepared[i + 1]
                    if nxt in '"\\':
                        text.append(nxt)
                        flags.append("e")
                    else:  # shlex keeps the backslash; `\$` stays a literal dollar
                        text.append(c + nxt)
                        flags.append("d" + ("e" if nxt == "$" else "d"))
                    i += 2
                    continue
                text.append(c)
                flags.append("d")
                i += 1
        elif c == "\\":
            if i + 1 >= n:
                raise Denied("unparseable command (No escaped character)")
            text.append(prepared[i + 1])
            flags.append("e")
            in_word, i = True, i + 2
        else:
            text.append(c)
            flags.append("u")
            in_word, i = True, i + 1
    flush()
    return words


def _split_punct(run: str) -> list:
    out, i = [], 0
    while i < len(run):
        op = next(o for o in _PUNCT_TOKENS if run.startswith(o, i))
        out.append(op)
        i += len(op)
    return out


def parse_command(command: str) -> list:
    """Segments of a Bash command. The posix shlex split stays the reference; the quote-aware pass must agree
    with it word for word, else the command is denied (fail closed)."""
    prepared = _unquoted_newlines_to_separators(command)
    tokens = _shlex_tokens(prepared)
    words = _scan_words(prepared)
    if [w.text for w in words] != tokens:
        raise Denied("unparseable command (the quoting analysis disagrees with the shell split)")
    segments, ops, depth, pending = [], [], 0, None
    cur = Segment(0)
    for w in words:
        if not w.flags or set(w.flags) != {"p"}:
            if pending:
                cur.redirs.append((pending, w))
                pending = None
            else:
                cur.words.append(w)
            continue
        for op in _split_punct(w.text):
            if op in REDIRECTIONS:
                if pending:
                    raise Denied(f"redirection `{pending}` without a target")
                pending = op
                continue
            if pending:
                raise Denied(f"redirection `{pending}` without a target")
            if cur.words or cur.redirs:
                cur.ops_before, ops = ops, []
                segments.append(cur)
                cur = Segment(depth)
            ops.append(op)
            depth += {"(": 1, ")": -1}.get(op, 0)
            if depth < 0:
                raise Denied("unbalanced parentheses")
            cur.depth = depth
    if pending:
        raise Denied(f"redirection `{pending}` without a target")
    if depth:
        raise Denied("unbalanced parentheses")
    if cur.words or cur.redirs:
        cur.ops_before, ops = ops, []
        segments.append(cur)
    for k, seg in enumerate(segments):
        seg.ops_after = segments[k + 1].ops_before if k + 1 < len(segments) else ops
    return segments


def split_segments(command: str) -> list:
    """Word texts per segment (redirections excluded)."""
    return [[w.text for w in seg.words] for seg in parse_command(command)]


# --------------------------------------------------------------------------------------------------
# Bash: expansions, programs and paths
# --------------------------------------------------------------------------------------------------
def _glob_marks(word: Word) -> list:
    """Per character: True for an active glob character (an unquoted *, ? or [, but not the ? of `$?`)."""
    t, f = word.text, word.flags
    return [c in "*?[" and f[i] == "u" and not (c == "?" and i and t[i - 1] == "$" and f[i - 1] == "u")
            for i, c in enumerate(t)]


def _has_glob(word: Word) -> bool:
    return any(_glob_marks(word))


def _is_status(t: str, f: str, i: int) -> bool:
    """`$?` (the last exit status, digits only) at index i, both characters in the same quoting."""
    return t[i:i + 2] == "$?" and f[i] == f[i + 1]


def _check_expansions(word: Word, allow_status: bool = False) -> None:
    """Expansions the guard cannot resolve: `$` outside single quotes, `~user` / `~+` / `~-`, `~` (home) and
    unquoted brace expansion. Single-quoted and escaped text is literal. `allow_status`: echo / printf text may use
    `$?`; it never reaches a path, a cd or a program name."""
    t, f = word.text, word.flags
    for i, c in enumerate(t):
        nxt = t[i + 1] if i + 1 < len(t) else ""
        if allow_status and c == "$" and f[i] in "ud" and _is_status(t, f, i):
            continue
        if c == "$" and f[i] in "ud" and nxt and (nxt in EXPANSION_START or (f[i] == "u" and f[i + 1] in "sd")):
            raise Denied(f"{t}: shell expansion `$...` outside single quotes is not allowed (the guard cannot "
                         "resolve it)")
        if c == "~" and f[i] == "u" and (i == 0 or (t[i - 1] in "=:" and f[i - 1] == "u")):
            if nxt in ("", "/"):
                raise Denied(f"{t}: home-directory paths are off limits")
            raise Denied(f"{t}: tilde expansion (~user, ~+, ~-) is not allowed")
    opened = None
    for i, c in enumerate(t):
        if f[i] != "u":
            continue
        if c == "{":
            opened = i
        elif c == "}" and opened is not None:
            inner = [(t[k], f[k]) for k in range(opened + 1, i)]
            if any(ch == "," and fl == "u" for ch, fl in inner) or any(
                    inner[k] == (".", "u") and inner[k + 1] == (".", "u") for k in range(len(inner) - 1)):
                raise Denied(f"{t}: brace expansion is not allowed (spell out each path)")
            opened = None


def _unwrap(words: list) -> tuple:
    """Skips VAR=value prefixes and wrapper programs with their options. Returns ([program, args...], the
    variable names assigned on the way, whether xargs feeds the program)."""
    words, assigned, via_xargs = list(words), [], False
    while words:
        if ASSIGNMENT_RE.match(words[0]):
            assigned.append(words.pop(0).split("=", 1)[0])
            continue
        prog = os.path.basename(words[0])
        if prog not in WRAPPERS:
            break
        if via_xargs:
            raise Denied(f"xargs feeding `{prog}` is not allowed (its program and arguments would come from stdin; "
                         f"xargs may feed only {', '.join(sorted(XARGS_PROGRAMS))})")
        words.pop(0)
        via_xargs = via_xargs or prog == "xargs"
        with_arg = WRAPPER_FLAGS_WITH_ARG.get(prog, set())
        while words and words[0].startswith("-"):
            flag = words.pop(0)
            short = flag[1:] if not flag.startswith("--") else ""
            if prog == "env" and (flag.startswith("--split-string") or "S" in short):
                raise Denied("env -S (string splitting) is not allowed")
            if prog == "env" and (flag.startswith("--chdir") or "C" in short):
                raise Denied("env -C / --chdir is not allowed (relative paths would escape the checks)")
            if flag in with_arg and words:
                words.pop(0)
        if prog == "env":
            while words and ASSIGNMENT_RE.match(words[0]):
                assigned.append(words.pop(0).split("=", 1)[0])
        if prog == "timeout" and words:
            words.pop(0)  # the duration
    return words, assigned, via_xargs


def check_git(args: list) -> None:
    i = 0
    while i < len(args) and args[i].startswith("-"):
        opt = args[i]
        if opt == "-c" or opt.startswith("-c") or opt.startswith("--config-env") or opt.startswith("--exec-path"):
            raise Denied("git -c / --config-env / --exec-path can run arbitrary commands")
        if opt in ("-C", "--git-dir", "--work-tree", "--namespace"):
            i += 2
            continue
        i += 1
    if i >= len(args):
        raise Denied("bare `git` (no subcommand)")
    sub = args[i]
    if sub not in GIT_READ_SUBCOMMANDS:
        raise Denied(f"`git {sub}` is not a read-only git subcommand (the orchestrator commits, pushes and "
                     "manages branches; never stage, commit, stash, checkout, reset, merge or push)")
    for a in args[i + 1:]:
        if any(a == d or a.startswith(d + "=") or (d == "-O" and a.startswith("-O")) for d in GIT_DENIED_ARGS):
            raise Denied(f"`git {sub} {a}` can run an external program or write a file")


def check_python(args: list, cwd: str = "", tree: str = "") -> None:
    i = 0
    while i < len(args):
        a = args[i]
        if a in PYTHON_FLAGS_WITH_ARG:
            i += 2
            continue
        if a.startswith("-W") or a.startswith("-X"):
            i += 1
            continue
        if a == "-m":
            if i + 1 >= len(args):
                raise Denied("python -m without a module")
            if args[i + 1].split(".")[0] not in PYTHON_MODULES:
                raise Denied(f"python -m {args[i + 1]} is not allowed (only {sorted(PYTHON_MODULES)})")
            return
        if a.startswith("-m") and len(a) > 2:
            return check_python(["-m", a[2:]] + args[i + 1:], cwd, tree)
        if a == "-c" or (a.startswith("-") and "c" in a[1:] and not a.startswith("--")):
            raise Denied("python -c (inline code) is not allowed; write a test under tests/ instead")
        if a == "-":
            raise Denied("python reading code from stdin is not allowed")
        if a.startswith("-") and len(a) > 1 and set(a[1:]) <= PYTHON_FLAGS_NO_ARG:
            i += 1
            continue
        if a.startswith("-"):
            raise Denied(f"python option {a} is not allowed")
        real = os.path.realpath(a if os.path.isabs(a) else os.path.join(cwd or ".", a))
        if tree and Confinement._under(real, tree):
            rel = os.path.relpath(real, tree).replace(os.sep, "/")
            if PYTHON_SCRIPT_RE.match(rel):
                return
        raise Denied(f"python {a}: only tests under tests/ and scripts/dev/sync_claude_assets.py of the issue "
                     "worktree may be run (desk scripts can reach the exchange, GitHub or the ledger)")
    raise Denied("interactive python (no script or module) is not allowed")


def _sed_in_place(args: list) -> bool:
    for a in args:
        if a.startswith("--in-place"):
            return True
        if a.startswith("-") and not a.startswith("--"):
            for c in a[1:]:
                if c == "i":
                    return True
                if c in "efl":  # the rest of the cluster is the option's value
                    break
    return False


def check_program(words: list, cwd: str = "", tree: str = "", assigned=(), via_xargs: bool = False) -> None:
    """`words` is [program, args...] after _unwrap."""
    if not words:
        if assigned:
            raise Denied("a segment that only assigns variables (VAR=value; ...) is not allowed")
        return
    program, args = words[0], words[1:]
    name = os.path.basename(program)
    if name in SHELL_KEYWORDS:
        raise Denied(f"`{name}`: shell compound commands (if, for, while, case, {{ }}) are not allowed; run "
                     "simple commands")
    if name == "cd":
        raise Denied("cd is allowed only as a plain `cd <directory>` segment")
    if PYTHON_NAME_RE.match(name):
        check_python(args, cwd, tree)
    elif name == "git":
        check_git(args)
    else:
        if name in DENIED_PROGRAMS or name.lower() in DENIED_PROGRAMS:
            raise Denied(f"`{name}` is not available to the issue fixer")
        if "/" in program or "\\" in program or name.endswith((".sh", ".py", ".ps1", ".bat", ".cmd", ".exe")):
            raise Denied(f"direct execution of `{program}` is not allowed (only tests via python -m unittest)")
        if name == "find" and any(a in FIND_EXEC_ARGS for a in args):
            raise Denied("find -exec/-ok/-fprint/-delete can run programs or write files; pipe to grep instead")
        if name == "sed" and any(SED_EXEC_RE.search(a) for a in args if not a.startswith("-") or a == "-e"):
            raise Denied("sed e/w commands can run programs or write arbitrary files; use the Edit tool")
    if via_xargs and name not in XARGS_PROGRAMS:
        raise Denied(f"xargs feeding `{name}` is not allowed (its arguments come from stdin, unseen by the guard; "
                     f"xargs may feed only {', '.join(sorted(XARGS_PROGRAMS))})")
    bad = sorted(n for n in assigned if n not in ENV_ALLOWED)
    if bad:
        raise Denied(f"environment variable {bad[0]} is not allowed (allowed: {', '.join(sorted(ENV_ALLOWED))})")


def _arg_roles(name: str, args: list) -> list:
    """[(Word, role)] for a program's arguments: read, write, maybe_write (unknown program: path-like arguments
    get the write rules) or skip (not a path: a pattern, a sed script, echo text)."""
    if name in NO_PATH_PROGRAMS:
        return [(a, SKIP) for a in args]
    if name == "dd":
        roles = {"of": WRITE, "if": READ}
        return [(a.tail(a.text.index("=") + 1), roles[a.text.split("=", 1)[0]])
                if a.text.split("=", 1)[0] in roles and "=" in a.text else (a, SKIP) for a in args]
    if name in READ_PROGRAMS or PYTHON_NAME_RE.match(name):
        default = READ
    else:
        default = WRITE if name in WRITE_PROGRAMS else MAYBE_WRITE
    value_default = MAYBE_WRITE if default == MAYBE_WRITE else READ
    short, long_ = SHORT_VALUE_OPTS.get(name, ""), LONG_VALUE_OPTS.get(name, set())
    roles_of = VALUE_ROLES.get(name, {})
    out, positional, explicit_script, in_place, target_given, opts_done, i = [], [], False, False, False, False, 0

    def value(opt, word):
        nonlocal explicit_script, target_given
        role = roles_of.get(opt, value_default)
        explicit_script = explicit_script or (name in PATTERN_PROGRAMS and opt in SCRIPT_OPTS)
        target_given = target_given or (role == WRITE and name in ("cp", "mv", "install"))
        out.append((word, role))

    while i < len(args):
        a, t = args[i], args[i].text
        if opts_done or not t.startswith("-") or t == "-":
            positional.append(a)
        elif t == "--":
            opts_done = True
        elif t.startswith("--"):
            key, eq, _ = t.partition("=")
            in_place = in_place or (name == "sed" and key == "--in-place")
            if eq:
                value(key, a.tail(len(key) + 1))
            elif key in long_ and i + 1 < len(args):
                i += 1
                value(key, args[i])
        else:
            for j in range(1, len(t)):
                if name == "sed" and t[j] == "i":
                    in_place = True  # the rest of the cluster is the backup suffix
                    break
                if t[j] in short:
                    if j + 1 < len(t):
                        value("-" + t[j], a.tail(j + 1))
                    elif i + 1 < len(args):
                        i += 1
                        value("-" + t[j], args[i])
                    break
        i += 1
    if name in PATTERN_PROGRAMS and not explicit_script and positional:
        out.append((positional.pop(0), SKIP))
    for k, a in enumerate(positional):
        if name == "cp":
            role = READ if target_given or k < len(positional) - 1 else WRITE
        elif name == "uniq":
            role = WRITE if k == 1 else READ
        elif name == "sed":
            role = WRITE if in_place else READ
        else:
            role = default
        out.append((a, role))
    return out


class _PathContext:
    def __init__(self, cwd: str, tree: str, conf: Confinement):
        self.cwd, self.tree, self.conf = cwd, tree, conf

    def resolve(self, text: str) -> str:
        return os.path.realpath(text if os.path.isabs(text) else os.path.join(self.cwd, text))


def _check_target(shown: str, real: str, write: bool, ctx: _PathContext, prefix_ok: bool) -> None:
    conf = ctx.conf
    if conf.in_main(real):
        raise Denied(f"{shown} resolves into the main checkout, which is off limits")
    other = conf.worktree_of(real)
    if other and other != ctx.tree:
        raise Denied(f"{shown} is in another issue worktree ({other}); a command may only use its own issue "
                     "worktree")
    if other:
        if write:
            _check_tree_write(shown, real, ctx.tree)
        return
    if real == os.devnull:
        return
    if any(Confinement._under(real, root) and not (write and real == root) for root in TEMP_ROOTS):
        return
    if prefix_ok and not write and any(Confinement._under(real, p) for p in PYTHON_PREFIXES):
        return
    home = os.path.realpath(os.path.expanduser("~"))
    where = "the home directory" if Confinement._under(real, home) else "outside the issue worktree"
    raise Denied(f"{shown} resolves to {where} ({real}); Bash may only {'write' if write else 'use'} paths inside "
                 "the issue worktree, /dev/null or the temp dir")


def _check_word(word: Word, role: str, ctx: _PathContext, prefix_ok: bool, write_program: bool) -> None:
    marks = _glob_marks(word)
    if role == SKIP:
        if not any(marks):
            return
        if write_program:
            raise Denied(f"{word.text}: an unquoted glob in a write command is not allowed")
        role = READ  # the shell expands it into file names
    write = role in (WRITE, MAYBE_WRITE)
    if any(marks):
        if role == WRITE:
            raise Denied(f"{word.text}: a glob cannot be a write target (name each file)")
        if role == MAYBE_WRITE:
            # Python's glob does not read every pattern as bash does ([^x], [[:alpha:]], quoted characters in a
            # bracket), so a program that may write never gets one
            raise Denied(f"{word.text}: an unquoted glob is not allowed in the arguments of a program the guard "
                         "does not know (it may write; name each file)")
        # The directory part before the first glob component is the same for every expansion
        first = marks.index(True)
        _check_target(word.text, ctx.resolve(word.text[:word.text.rfind("/", 0, first) + 1]), False, ctx,
                      prefix_ok)
        pattern = "".join(c if m else glob.escape(c) for c, m in zip(word.text, marks))
        matches = glob.glob(pattern if os.path.isabs(pattern) else os.path.join(ctx.cwd, pattern))
        if matches:
            for m in matches:
                _check_target(word.text, os.path.realpath(m), False, ctx, prefix_ok)
            return
        # No match: bash passes the word unchanged, so the literal is checked below too
    real = ctx.resolve(word.text)
    if role != WRITE and not (os.path.exists(real) or os.path.isdir(os.path.dirname(real))):
        return  # not a path (e.g. "/fapi/v1/order")
    _check_target(word.text, real, write, ctx, prefix_ok)


def check_paths(words: list, redirs: list, ctx: _PathContext) -> None:
    """`words` is [program, args...] as Words after _unwrap; `redirs` the segment's redirections."""
    for op, target in redirs:
        if op in (">&", "<&") and (target.text.isdigit() or target.text == "-"):
            continue  # file descriptor duplication
        _check_word(target, READ if op in ("<", "<&") else WRITE, ctx, False, True)
    if not words:
        return
    name = os.path.basename(words[0].text)
    prefix_ok = name in READ_PROGRAMS or bool(PYTHON_NAME_RE.match(name))
    in_place = name == "sed" and _sed_in_place([w.text for w in words[1:]])
    write_program = name in WRITE_PROGRAMS or in_place
    for word, role in _arg_roles(name, words[1:]):
        _check_word(word, role, ctx, prefix_ok, write_program)


def _check_cd(segments: list, i: int, cwd: str, tree: str, conf: Confinement) -> str:
    """A `cd` after the first one; returns the new tracked directory."""
    seg = segments[i]
    if len(seg.words) != 2 or seg.redirs:
        raise Denied("cd takes exactly one directory")
    if seg.depth:
        raise Denied("cd inside a subshell ( ... ) is not allowed (the guard could not track the directory)")
    if any(o in ("|", "|&", "||") for o in seg.ops_before) or seg.next in ("|", "|&", "&", "||"):
        raise Denied("cd in a pipeline, in the background or next to || is not allowed")
    if "&&" in seg.ops_before:
        # Conditional cd: when it is skipped, nothing after it may run with the untracked directory
        k = i
        while k > 0 and not any(o in LIST_SEPARATORS for o in segments[k].ops_before):
            if "||" in segments[k].ops_before:
                raise Denied("a conditional cd after || is not allowed")
            k -= 1
        if any(o not in ("&&", "|", "|&") for s in segments[i + 1:] for o in s.ops_before):
            raise Denied("a conditional cd (`... && cd X`) may not be followed by ;, &, || or a subshell")
    word = seg.words[1]
    _check_expansions(word)
    if word.text == "-" or _has_glob(word):
        raise Denied(f"cd {word.text} is not allowed (name the directory)")
    target = os.path.realpath(word.text if os.path.isabs(word.text) else os.path.join(cwd, word.text))
    if conf.in_main(target) or conf.worktree_of(target) != tree:
        raise Denied(f"cd {word.text} leaves the issue worktree")
    if not os.path.isdir(target):
        raise Denied(f"cd {word.text}: not an existing directory of the issue worktree")
    return target


def _first_cd(segments: list, conf: Confinement) -> tuple:
    """(issue worktree, tracked directory) from the mandatory leading `cd <absolute path>`."""
    first = segments[0] if segments else None
    if (not first or first.depth or first.ops_before or first.redirs or len(first.words) != 2
            or first.words[0].text != "cd" or first.next not in ("&&", ";", None)):
        raise Denied(START_MESSAGE)
    _check_expansions(first.words[1])
    target = first.words[1].text
    if _has_glob(first.words[1]) or not os.path.isabs(target):
        raise Denied(START_MESSAGE)
    real = os.path.realpath(target)
    tree = conf.worktree_of(real)
    if not tree or conf.in_main(real) or not os.path.isdir(real):
        raise Denied(START_MESSAGE)
    return tree, real


def evaluate(command, conf: Confinement) -> str:
    """Returns '' when the Bash command is allowed, else the denial reason. Pure: reads the filesystem only."""
    if not isinstance(command, str) or not command.strip():
        return "empty or missing command"
    for pattern, what in RAW_DENY:
        if pattern.search(command):
            return f"{what} is not allowed in the issue fixer"
    try:
        segments = parse_command(command)
        tree, cwd = _first_cd(segments, conf)
        for i in range(1, len(segments)):
            seg = segments[i]
            if seg.words and seg.words[0].text == "cd":
                cwd = _check_cd(segments, i, cwd, tree, conf)
                continue
            texts = [w.text for w in seg.words]
            rest, assigned, via_xargs = _unwrap(texts)
            start = len(texts) - len(rest)
            # `$?` only in the arguments of echo / printf (text), never in a program name, path or redirection
            status_ok = bool(rest) and os.path.basename(rest[0]) in NO_PATH_PROGRAMS
            for k, w in enumerate(seg.words):
                _check_expansions(w, status_ok and k > start)
            for _, t in seg.redirs:
                _check_expansions(t)
            check_paths(seg.words[start:], seg.redirs, _PathContext(cwd, tree, conf))
            check_program(rest, cwd, tree, assigned, via_xargs)
    except Denied as e:
        return str(e)
    return ""


# --------------------------------------------------------------------------------------------------
# Binding and heartbeat
# --------------------------------------------------------------------------------------------------
def payload_worktree(payload: dict, conf: Confinement) -> str:
    """The issue worktree a call works in: the first `cd` of a Bash command or the edit target ('' if none)."""
    tool_input = payload.get("tool_input")
    if not isinstance(tool_input, dict):
        return ""
    if payload.get("tool_name") == "Bash":
        command = tool_input.get("command")
        try:
            segments = parse_command(command) if isinstance(command, str) else []
        except Denied:
            return ""
        first = segments[0].words if segments else []
        if len(first) == 2 and first[0].text == "cd" and os.path.isabs(first[1].text):
            return conf.worktree_of(first[1].text)
        return ""
    path = tool_input.get("file_path") or tool_input.get("notebook_path")
    return conf.worktree_of(path) if isinstance(path, str) and os.path.isabs(path) else ""


def _read_binding(tree: str):
    path = os.path.join(tree, WORK_DIR, BINDING_FILE)
    if not os.path.lexists(path):
        return None
    try:
        with open(path, encoding="utf-8") as f:
            marker = json.load(f)
    except (OSError, ValueError) as e:
        raise Denied(f"unreadable binding marker {path} ({e})")
    if not isinstance(marker, dict):
        raise Denied(f"malformed binding marker {path}")
    return marker


def check_binding(tree: str, session_id) -> None:
    """Read-only. No marker: legacy worktree, accepted unbound. A marker that names another worktree or holds
    another session id denies."""
    if not tree:
        return
    marker = _read_binding(tree)
    if marker is None:
        return
    named = marker.get("worktree")
    if not isinstance(named, str) or os.path.realpath(named) != tree:
        raise Denied(f"the binding marker of {tree} names another worktree ({named!r})")
    bound = marker.get("session_id")
    if bound is not None and not isinstance(bound, str):
        raise Denied(f"malformed session_id in the binding marker of {tree}")
    if isinstance(session_id, str) and session_id and bound and bound != session_id:
        raise Denied(f"worktree {tree} is bound to another session (issue #{marker.get('issue')})")


def _atomic_write_json(path: str, data: dict) -> None:
    tmp = f"{path}.{os.getpid()}.tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f)
    os.replace(tmp, path)


def claim_binding(tree: str, session_id) -> None:
    """Best effort: an unclaimed marker records the first session id that works in the worktree."""
    if not tree or not isinstance(session_id, str) or not session_id:
        return
    try:
        marker = _read_binding(tree)
        if marker is None or marker.get("session_id"):
            return
        marker["session_id"] = session_id
        _atomic_write_json(os.path.join(tree, WORK_DIR, BINDING_FILE), marker)
    except Exception:  # noqa: BLE001 - never change the decision on a write error
        pass


def write_heartbeat(tree: str, tool, reason: str, session_id) -> None:
    """Best effort: proves to the orchestrator (issue_workspace.py check-guard) that the guard ran."""
    if not tree:
        return
    try:
        work = os.path.join(tree, WORK_DIR)
        os.makedirs(work, exist_ok=True)
        _atomic_write_json(os.path.join(work, HEARTBEAT_FILE), {
            "ts": int(time.time()), "tool": tool if isinstance(tool, str) else None,
            "decision": "deny" if reason else "allow", "reason": reason or None,
            "session_id": session_id if isinstance(session_id, str) else None})
    except Exception:  # noqa: BLE001 - never change the decision on a write error
        pass


def evaluate_payload(payload: dict, conf: Confinement) -> str:
    tool = payload.get("tool_name")
    tool_input = payload.get("tool_input") or {}
    if tool not in EDIT_TOOLS | {"Bash"}:
        return ""
    if not isinstance(tool_input, dict):
        return "tool_input is not an object"
    try:
        if tool == "Bash":
            reason = evaluate(tool_input.get("command"), conf)
            if reason:
                return reason
        else:
            check_edit_path(tool_input.get("file_path") or tool_input.get("notebook_path"), conf)
        check_binding(payload_worktree(payload, conf), payload.get("session_id"))
    except Denied as e:
        return str(e)
    return ""


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (ValueError, OSError) as e:
        print(f"issue_fixer_guard: unreadable hook input ({e}); denied (fail closed).", file=sys.stderr)
        return 2
    if not isinstance(payload, dict):
        print("issue_fixer_guard: hook input is not an object; denied (fail closed).", file=sys.stderr)
        return 2
    if payload.get("tool_name") not in EDIT_TOOLS | {"Bash"}:
        return 0
    try:
        conf = Confinement.from_project_dir(os.environ.get("CLAUDE_PROJECT_DIR") or payload.get("cwd") or ".")
    except (Denied, OSError, subprocess.SubprocessError) as e:
        print(f"issue_fixer_guard: {e}; denied (fail closed).", file=sys.stderr)
        return 2
    try:
        reason = evaluate_payload(payload, conf)
    except Exception as e:  # noqa: BLE001 - an unexpected error must deny, never fall through
        reason = f"internal guard error ({type(e).__name__}: {e})"
    try:
        tree = payload_worktree(payload, conf)
    except Exception:  # noqa: BLE001
        tree = ""
    session_id = payload.get("session_id")
    if not reason:
        claim_binding(tree, session_id)
    write_heartbeat(tree, payload.get("tool_name"), reason, session_id)
    if reason:
        print(f"BLOCKED by issue_fixer_guard: {reason}. This guard is a confinement policy, not a sandbox (a "
              "denylist plus path rules; Claude Code only). Work only inside the issue worktree; allowed shell: "
              "read-only tools, read-only git, python -m unittest/compileall/py_compile/pytest, tests under "
              "tests/ and scripts/dev/sync_claude_assets.py. Report anything else to the orchestrator in your "
              "final response instead of working around it.", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
