#!/usr/bin/env python3
"""
issue_fixer_guard.py - PreToolUse hook scoped to the `issue_fixer` subagent (Claude Code frontmatter hook,
generated by scripts/dev/sync_claude_assets.py). The project hooks (pre_trade_guard.py) still run as well.

The fixer edits code and runs tests inside an issue worktree; it never commits, pushes, calls GitHub or the
network, installs packages or runs desk runtime scripts. This guard enforces that for its Bash calls with an
ALLOWLIST, so anything it does not recognise is denied:

  * every shell segment (split on ; && || | & newlines and subshell parentheses) is checked;
    `VAR=value` prefixes and wrappers (env, timeout, nice, nohup, time, command, stdbuf, xargs) are unwrapped;
  * command substitution ($(...), backticks), process substitution, heredocs (<<) and `eval` / `sh -c` style
    indirection are denied outright (use the Write/Edit tools to create files);
  * git: read-only subcommands only (diff, status, log, show, grep, ls-files, blame, rev-parse, ...);
  * python: only `-m unittest|compileall|py_compile|pytest`, a test file under tests/, or
    scripts/dev/sync_claude_assets.py (any other script, `-c` code or stdin is denied);
  * network, package managers, GitHub CLI, other interpreters and shells, privilege escalation and
    direct execution of scripts (./x.sh, scripts/...) are denied.

Contract (Claude Code hooks): reads the hook JSON on stdin; exit 0 allows, exit 2 denies (reason on stderr).
Malformed input is denied (fail closed). Non-Bash tools are allowed (the fixer's tool list is fixed in its
frontmatter).
"""

import json
import os
import re
import shlex
import sys

GIT_READ_SUBCOMMANDS = {
    "diff", "status", "log", "show", "grep", "ls-files", "blame", "rev-parse", "describe", "shortlog",
    "cat-file", "ls-tree", "merge-base", "diff-tree", "name-rev", "rev-list", "whatchanged",
}
GIT_DENIED_ARGS = ("--ext-diff", "-O", "--open-files-in-pager", "--output")
PYTHON_MODULES = {"unittest", "compileall", "py_compile", "pytest"}
PYTHON_FLAGS_NO_ARG = set("bBdEhiIOqsSuvVxR")
PYTHON_FLAGS_WITH_ARG = {"-W", "-X"}
PYTHON_SCRIPT_RE = re.compile(r"(^|/)(tests/[\w./-]+\.py|scripts/dev/sync_claude_assets\.py)$")
PYTHON_NAME_RE = re.compile(r"^(python|python3(\.\d+)?|py)$")

DENIED_PROGRAMS = {
    # GitHub / network / remote access
    "gh", "curl", "wget", "ssh", "scp", "sftp", "rsync", "nc", "ncat", "netcat", "telnet", "ftp", "socat",
    # package managers
    "pip", "pip3", "pipx", "npm", "npx", "yarn", "pnpm", "apt", "apt-get", "brew", "conda", "uv", "poetry",
    # privilege, containers, OS bridges and services
    "sudo", "su", "doas", "docker", "podman", "kubectl", "wsl", "wsl.exe", "powershell", "powershell.exe",
    "pwsh", "cmd", "cmd.exe", "crontab", "systemctl", "service", "at", "pkill", "killall", "open", "xdg-open",
    # shells, indirection and other interpreters
    "eval", "exec", "source", ".", "bash", "sh", "zsh", "dash", "ksh", "fish", "perl", "ruby", "node", "deno",
    "php", "lua", "osascript",
}
WRAPPERS = {"env", "timeout", "nice", "nohup", "time", "command", "stdbuf", "xargs"}
WRAPPER_FLAGS_WITH_ARG = {
    "timeout": {"-s", "--signal", "-k", "--kill-after"},
    "nice": {"-n", "--adjustment"},
    "stdbuf": {"-i", "-o", "-e"},
    "xargs": {"-n", "-I", "-L", "-P", "-d", "-s", "-E", "-a", "--max-args", "--replace", "--max-lines",
              "--max-procs", "--delimiter", "--arg-file"},
    "env": {"-u", "--unset", "-C", "--chdir"},
}
RAW_DENY = [
    (re.compile(r"\$\("), "command substitution $(...)"),
    (re.compile(r"`"), "backtick command substitution"),
    (re.compile(r"[<>]\("), "process substitution"),
    (re.compile(r"<<"), "heredoc (use the Write/Edit tools to create files)"),
]
OPERATORS = {";", "&&", "||", "|", "&", "|&", "(", ")", ";;"}
ASSIGNMENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")


class Denied(Exception):
    pass


def _unquoted_newlines_to_separators(command: str) -> str:
    """Line continuations become spaces; unquoted newlines become ';' so every line is its own segment."""
    command = command.replace("\\\r\n", " ").replace("\\\n", " ")
    out, quote = [], None
    for ch in command:
        if quote:
            if ch == quote:
                quote = None
        elif ch in ("'", '"'):
            quote = ch
        elif ch in ("\n", "\r"):
            ch = ";"
        out.append(ch)
    return "".join(out)


def split_segments(command: str) -> list:
    lexer = shlex.shlex(_unquoted_newlines_to_separators(command), posix=True, punctuation_chars=";&|()<>")
    lexer.whitespace_split = True
    lexer.commenters = ""
    try:
        tokens = list(lexer)
    except ValueError as e:
        raise Denied(f"unparseable command ({e})")
    segments, current = [], []
    for tok in tokens:
        if tok in OPERATORS:
            if current:
                segments.append(current)
            current = []
        else:
            current.append(tok)
    if current:
        segments.append(current)
    return segments


def _strip_redirections(words: list) -> list:
    """Drops redirection operators and their targets (`> file`, `2>&1`, `< in`)."""
    out, skip = [], False
    for w in words:
        if skip:
            skip = False
            continue
        if re.fullmatch(r"[<>&]*[<>][<>&]*", w):
            skip = True
            continue
        out.append(w)
    return out


def _unwrap(words: list) -> list:
    """Skips VAR=value prefixes and wrapper programs with their options; returns [program, args...]."""
    words = list(words)
    while words:
        if ASSIGNMENT_RE.match(words[0]):
            words.pop(0)
            continue
        prog = os.path.basename(words[0])
        if prog not in WRAPPERS:
            return words
        words.pop(0)
        with_arg = WRAPPER_FLAGS_WITH_ARG.get(prog, set())
        while words and words[0].startswith("-"):
            flag = words.pop(0)
            if flag in with_arg and words:
                words.pop(0)
        if prog == "env":
            while words and ASSIGNMENT_RE.match(words[0]):
                words.pop(0)
        if prog == "timeout" and words:
            words.pop(0)  # the duration
    return words


def check_git(args: list) -> None:
    i = 0
    while i < len(args) and args[i].startswith("-"):
        opt = args[i]
        if opt == "-c" or opt.startswith("-c") or opt.startswith("--config-env") or opt.startswith("--exec-path"):
            raise Denied("git -c / --config-env / --exec-path can run arbitrary commands")
        if opt in ("-C", "--git-dir", "--work-tree", "--namespace"):
            i += 2
            continue
        i += 1
    if i >= len(args):
        raise Denied("bare `git` (no subcommand)")
    sub = args[i]
    if sub not in GIT_READ_SUBCOMMANDS:
        raise Denied(f"`git {sub}` is not a read-only git subcommand (the orchestrator commits, pushes and "
                     "manages branches; never stage, commit, stash, checkout, reset, merge or push)")
    for a in args[i + 1:]:
        if any(a == d or a.startswith(d + "=") or (d == "-O" and a.startswith("-O")) for d in GIT_DENIED_ARGS):
            raise Denied(f"`git {sub} {a}` can run an external program or write a file")


def check_python(args: list) -> None:
    i = 0
    while i < len(args):
        a = args[i]
        if a in PYTHON_FLAGS_WITH_ARG:
            i += 2
            continue
        if a.startswith("-W") or a.startswith("-X"):
            i += 1
            continue
        if a == "-m":
            if i + 1 >= len(args):
                raise Denied("python -m without a module")
            if args[i + 1].split(".")[0] not in PYTHON_MODULES:
                raise Denied(f"python -m {args[i + 1]} is not allowed (only {sorted(PYTHON_MODULES)})")
            return
        if a.startswith("-m") and len(a) > 2:
            return check_python(["-m", a[2:]] + args[i + 1:])
        if a == "-c" or (a.startswith("-") and "c" in a[1:] and not a.startswith("--")):
            raise Denied("python -c (inline code) is not allowed; write a test under tests/ instead")
        if a == "-":
            raise Denied("python reading code from stdin is not allowed")
        if a.startswith("-") and len(a) > 1 and set(a[1:]) <= PYTHON_FLAGS_NO_ARG:
            i += 1
            continue
        if a.startswith("-"):
            raise Denied(f"python option {a} is not allowed")
        if PYTHON_SCRIPT_RE.search(a.replace("\\", "/")):
            return
        raise Denied(f"python {a}: only tests under tests/ and scripts/dev/sync_claude_assets.py may be run "
                     "(desk scripts can reach the exchange, GitHub or the ledger)")
    raise Denied("interactive python (no script or module) is not allowed")


def check_segment(words: list) -> None:
    words = _unwrap(_strip_redirections(words))
    if not words:
        return
    program, args = words[0], words[1:]
    name = os.path.basename(program)
    if PYTHON_NAME_RE.match(name):
        return check_python(args)
    if name == "git":
        return check_git(args)
    if name in DENIED_PROGRAMS or name.lower() in DENIED_PROGRAMS:
        raise Denied(f"`{name}` is not available to the issue fixer")
    if "/" in program or "\\" in program or name.endswith((".sh", ".py", ".ps1", ".bat", ".cmd", ".exe")):
        raise Denied(f"direct execution of `{program}` is not allowed (only tests via python -m unittest)")


def evaluate(command: str) -> str:
    """Returns '' when the command is allowed, else the denial reason."""
    if not isinstance(command, str) or not command.strip():
        return "empty or missing command"
    for pattern, what in RAW_DENY:
        if pattern.search(command):
            return f"{what} is not allowed in the issue fixer"
    try:
        for seg in split_segments(command):
            check_segment(seg)
    except Denied as e:
        return str(e)
    return ""


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (ValueError, OSError) as e:
        print(f"issue_fixer_guard: unreadable hook input ({e}); denied (fail closed).", file=sys.stderr)
        return 2
    if not isinstance(payload, dict):
        print("issue_fixer_guard: hook input is not an object; denied (fail closed).", file=sys.stderr)
        return 2
    if payload.get("tool_name") != "Bash":
        return 0
    command = (payload.get("tool_input") or {}).get("command")
    reason = evaluate(command)
    if reason:
        print(f"BLOCKED by issue_fixer_guard: {reason}. Allowed: read-only shell tools, read-only git, "
              "python -m unittest/compileall/py_compile/pytest, tests under tests/ and "
              "scripts/dev/sync_claude_assets.py. Report anything else to the orchestrator in your final "
              "response instead of working around it.", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
