#!/usr/bin/env python3
"""
issue_fixer_guard.py - PreToolUse hook scoped to the `issue_fixer` subagent (Claude Code frontmatter hook,
generated by scripts/dev/sync_claude_assets.py; matcher Bash|Edit|Write|MultiEdit|NotebookEdit). The project
hooks (pre_trade_guard.py) still run as well and stay the hard boundary for trading actions.

The fixer edits code and runs tests inside ONE linked issue worktree; it never commits, pushes, calls GitHub or
the network, installs packages, runs desk runtime scripts or touches the main checkout (where the running hooks,
this guard included, live). Confinement:

  * Edit / Write / MultiEdit / NotebookEdit: the absolute target must be inside a linked worktree of this
    repository (never the main checkout), and never under .git/, .claude/, .agents/hooks.json or logs/ (except
    logs/issue_work/).
  * Bash, with an ALLOWLIST so anything unrecognised is denied:
      - the command must start with `cd <absolute path of a linked worktree>`; later `cd`s may not leave it for
        the main checkout, and no argument may resolve into the main checkout or name $CLAUDE_PROJECT_DIR / ~;
      - every segment (split on ; && || | & newlines and subshell parentheses) is checked; `VAR=value` prefixes
        and wrappers (env, timeout, nice, nohup, time, command, stdbuf, xargs) are unwrapped;
      - command substitution, process substitution, heredocs and `eval` / `sh -c` style indirection are denied;
      - git: read-only subcommands only; python: only `-m unittest|compileall|py_compile|pytest`, test files
        under tests/ and scripts/dev/sync_claude_assets.py;
      - programs that can execute other programs (find -exec, awk, sed's e/w commands, make, editors, other
        interpreters and shells), network tools, package managers, GitHub CLI and privilege escalation are denied.

Limits: tests the fixer writes are code and run with the test runner; the auditor and the PR reviewers review that
code before merge. This guard prevents direct misuse; it is not a sandbox.

Contract (Claude Code hooks): hook JSON on stdin; exit 0 allows, exit 2 denies (reason on stderr). Malformed input
or an unresolvable repository is denied (fail closed).
"""

import json
import os
import re
import shlex
import subprocess
import sys

EDIT_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}
GIT_READ_SUBCOMMANDS = {
    "diff", "status", "log", "show", "grep", "ls-files", "blame", "rev-parse", "describe", "shortlog",
    "cat-file", "ls-tree", "merge-base", "diff-tree", "name-rev", "rev-list", "whatchanged",
}
GIT_DENIED_ARGS = ("--ext-diff", "-O", "--open-files-in-pager", "--output")
PYTHON_MODULES = {"unittest", "compileall", "py_compile", "pytest"}
PYTHON_FLAGS_NO_ARG = set("bBdEhiIOqsSuvVxR")
PYTHON_FLAGS_WITH_ARG = {"-W", "-X"}
PYTHON_SCRIPT_RE = re.compile(r"(^|/)(tests/[\w./-]+\.py|scripts/dev/sync_claude_assets\.py)$")
PYTHON_NAME_RE = re.compile(r"^(python|python3(\.\d+)?|py)$")

DENIED_PROGRAMS = {
    # GitHub / network / remote access
    "gh", "curl", "wget", "ssh", "scp", "sftp", "rsync", "nc", "ncat", "netcat", "telnet", "ftp", "socat",
    # package managers and build tools that run arbitrary recipes
    "pip", "pip3", "pipx", "npm", "npx", "yarn", "pnpm", "apt", "apt-get", "brew", "conda", "uv", "poetry",
    "make", "gmake", "cmake",
    # privilege, containers, OS bridges and services
    "sudo", "su", "doas", "docker", "podman", "kubectl", "wsl", "wsl.exe", "powershell", "powershell.exe",
    "pwsh", "cmd", "cmd.exe", "crontab", "systemctl", "service", "at", "pkill", "killall", "open", "xdg-open",
    # shells, indirection, interpreters and programs that execute other programs
    "eval", "exec", "source", ".", "bash", "sh", "zsh", "dash", "ksh", "fish", "perl", "ruby", "node", "deno",
    "php", "lua", "osascript", "awk", "gawk", "mawk", "nawk", "busybox", "watch", "parallel", "script",
    "expect", "tclsh", "strace", "gdb", "vi", "vim", "nvim", "emacs", "ed", "ex", "nano",
}
WRAPPERS = {"env", "timeout", "nice", "nohup", "time", "command", "stdbuf", "xargs"}
WRAPPER_FLAGS_WITH_ARG = {
    "timeout": {"-s", "--signal", "-k", "--kill-after"},
    "nice": {"-n", "--adjustment"},
    "stdbuf": {"-i", "-o", "-e"},
    "xargs": {"-n", "-I", "-L", "-P", "-d", "-s", "-E", "-a", "--max-args", "--replace", "--max-lines",
              "--max-procs", "--delimiter", "--arg-file"},
    "env": {"-u", "--unset", "-C", "--chdir"},
}
FIND_EXEC_ARGS = {"-exec", "-execdir", "-ok", "-okdir", "-fprint", "-fprint0", "-fprintf", "-fls"}
# sed `e` (execute) / `w` `W` (write file) commands, with an optional address (1e, $e, /re/e, 1,5w), and the
# s///e and s///w flags
_SED_ADDR = r"(?:\d+|\$|/(?:[^/\\]|\\.)*/)"
SED_EXEC_RE = re.compile(
    r"(^|[;{}\n])\s*(?:" + _SED_ADDR + r"(?:\s*,\s*" + _SED_ADDR + r")?)?\s*!?\s*[eWw](\s|;|$)"
    r"|/[0-9gpIiMm]*[ew][0-9gpIiMm]*\s*($|[;}\s])"
)
RAW_DENY = [
    (re.compile(r"\$\("), "command substitution $(...)"),
    (re.compile(r"`"), "backtick command substitution"),
    (re.compile(r"[<>]\("), "process substitution"),
    (re.compile(r"<<"), "heredoc (use the Write/Edit tools to create files)"),
    (re.compile(r"CLAUDE_PROJECT_DIR"), "$CLAUDE_PROJECT_DIR (the main checkout is off limits)"),
]
OPERATORS = {";", "&&", "||", "|", "&", "|&", "(", ")", ";;"}
ASSIGNMENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")


class Denied(Exception):
    pass


class Confinement:
    """The main checkout (off limits) and the linked worktrees (where the fixer may work)."""

    def __init__(self, main_root: str, worktrees: list):
        self.main_root = os.path.realpath(main_root)
        self.worktrees = [os.path.realpath(w) for w in worktrees if os.path.realpath(w) != self.main_root]

    @classmethod
    def from_project_dir(cls, project_dir: str) -> "Confinement":
        common = subprocess.run(["git", "rev-parse", "--path-format=absolute", "--git-common-dir"],
                                cwd=project_dir, capture_output=True, text=True, timeout=10)
        if common.returncode != 0:
            raise Denied(f"cannot resolve the repository from {project_dir}")
        main_root = os.path.dirname(common.stdout.strip().rstrip("/"))
        listing = subprocess.run(["git", "worktree", "list", "--porcelain"], cwd=main_root,
                                 capture_output=True, text=True, timeout=10)
        if listing.returncode != 0:
            raise Denied("cannot list the repository worktrees")
        trees = [ln[len("worktree "):] for ln in listing.stdout.splitlines() if ln.startswith("worktree ")]
        return cls(main_root, trees)

    @staticmethod
    def _under(path: str, root: str) -> bool:
        return path == root or path.startswith(root.rstrip(os.sep) + os.sep)

    def in_main(self, path: str) -> bool:
        return self._under(os.path.realpath(path), self.main_root)

    def worktree_of(self, path: str) -> str:
        real = os.path.realpath(path)
        return next((w for w in self.worktrees if self._under(real, w)), "")


# --------------------------------------------------------------------------------------------------
# Edit tools
# --------------------------------------------------------------------------------------------------
def check_edit_path(path, conf: Confinement) -> None:
    if not isinstance(path, str) or not path:
        raise Denied("missing file path")
    if not os.path.isabs(path):
        raise Denied(f"{path}: use an absolute path inside the issue worktree")
    tree = conf.worktree_of(path)
    if not tree or conf.in_main(path):
        raise Denied(f"{path} is outside the issue worktrees (the main checkout and other directories are off "
                     "limits)")
    rel = os.path.relpath(os.path.realpath(path), tree).replace(os.sep, "/")
    parts = rel.split("/")
    if ".git" in parts:
        raise Denied(f"{path}: git internals are off limits")
    if parts[0] == ".claude":
        raise Denied(f"{path}: .claude/ is generated or local configuration (edit .agents/ and run the generator)")
    if rel == ".agents/hooks.json":
        raise Denied(f"{path}: hook configuration is off limits")
    if parts[0] == "logs" and (len(parts) < 3 or parts[1] != "issue_work"):
        raise Denied(f"{path}: only logs/issue_work/ may be written under logs/")


# --------------------------------------------------------------------------------------------------
# Bash
# --------------------------------------------------------------------------------------------------
def _unquoted_newlines_to_separators(command: str) -> str:
    """Line continuations become spaces; unquoted newlines become ';' so every line is its own segment."""
    command = command.replace("\\\r\n", " ").replace("\\\n", " ")
    out, quote = [], None
    for ch in command:
        if quote:
            if ch == quote:
                quote = None
        elif ch in ("'", '"'):
            quote = ch
        elif ch in ("\n", "\r"):
            ch = ";"
        out.append(ch)
    return "".join(out)


def split_segments(command: str) -> list:
    lexer = shlex.shlex(_unquoted_newlines_to_separators(command), posix=True, punctuation_chars=";&|()<>")
    lexer.whitespace_split = True
    lexer.commenters = ""
    try:
        tokens = list(lexer)
    except ValueError as e:
        raise Denied(f"unparseable command ({e})")
    segments, current = [], []
    for tok in tokens:
        if tok in OPERATORS:
            if current:
                segments.append(current)
            current = []
        else:
            current.append(tok)
    if current:
        segments.append(current)
    return segments


def _strip_redirections(words: list) -> list:
    """Drops redirection operators and their targets (`> file`, `2>&1`, `< in`)."""
    out, skip = [], False
    for w in words:
        if skip:
            skip = False
            continue
        if re.fullmatch(r"[<>&]*[<>][<>&]*", w):
            skip = True
            continue
        out.append(w)
    return out


def _unwrap(words: list) -> list:
    """Skips VAR=value prefixes and wrapper programs with their options; returns [program, args...]."""
    words = list(words)
    while words:
        if ASSIGNMENT_RE.match(words[0]):
            words.pop(0)
            continue
        prog = os.path.basename(words[0])
        if prog not in WRAPPERS:
            return words
        words.pop(0)
        with_arg = WRAPPER_FLAGS_WITH_ARG.get(prog, set())
        while words and words[0].startswith("-"):
            flag = words.pop(0)
            if prog == "env" and (flag in ("-S", "--split-string") or flag.startswith("--split-string=")):
                raise Denied("env -S (string splitting) is not allowed")
            if flag in with_arg and words:
                words.pop(0)
        if prog == "env":
            while words and ASSIGNMENT_RE.match(words[0]):
                words.pop(0)
        if prog == "timeout" and words:
            words.pop(0)  # the duration
    return words


def check_git(args: list) -> None:
    i = 0
    while i < len(args) and args[i].startswith("-"):
        opt = args[i]
        if opt == "-c" or opt.startswith("-c") or opt.startswith("--config-env") or opt.startswith("--exec-path"):
            raise Denied("git -c / --config-env / --exec-path can run arbitrary commands")
        if opt in ("-C", "--git-dir", "--work-tree", "--namespace"):
            i += 2
            continue
        i += 1
    if i >= len(args):
        raise Denied("bare `git` (no subcommand)")
    sub = args[i]
    if sub not in GIT_READ_SUBCOMMANDS:
        raise Denied(f"`git {sub}` is not a read-only git subcommand (the orchestrator commits, pushes and "
                     "manages branches; never stage, commit, stash, checkout, reset, merge or push)")
    for a in args[i + 1:]:
        if any(a == d or a.startswith(d + "=") or (d == "-O" and a.startswith("-O")) for d in GIT_DENIED_ARGS):
            raise Denied(f"`git {sub} {a}` can run an external program or write a file")


def check_python(args: list) -> None:
    i = 0
    while i < len(args):
        a = args[i]
        if a in PYTHON_FLAGS_WITH_ARG:
            i += 2
            continue
        if a.startswith("-W") or a.startswith("-X"):
            i += 1
            continue
        if a == "-m":
            if i + 1 >= len(args):
                raise Denied("python -m without a module")
            if args[i + 1].split(".")[0] not in PYTHON_MODULES:
                raise Denied(f"python -m {args[i + 1]} is not allowed (only {sorted(PYTHON_MODULES)})")
            return
        if a.startswith("-m") and len(a) > 2:
            return check_python(["-m", a[2:]] + args[i + 1:])
        if a == "-c" or (a.startswith("-") and "c" in a[1:] and not a.startswith("--")):
            raise Denied("python -c (inline code) is not allowed; write a test under tests/ instead")
        if a == "-":
            raise Denied("python reading code from stdin is not allowed")
        if a.startswith("-") and len(a) > 1 and set(a[1:]) <= PYTHON_FLAGS_NO_ARG:
            i += 1
            continue
        if a.startswith("-"):
            raise Denied(f"python option {a} is not allowed")
        if PYTHON_SCRIPT_RE.search(a.replace("\\", "/")):
            return
        raise Denied(f"python {a}: only tests under tests/ and scripts/dev/sync_claude_assets.py may be run "
                     "(desk scripts can reach the exchange, GitHub or the ledger)")
    raise Denied("interactive python (no script or module) is not allowed")


def check_program(words: list) -> None:
    words = _unwrap(_strip_redirections(words))
    if not words:
        return
    program, args = words[0], words[1:]
    name = os.path.basename(program)
    if PYTHON_NAME_RE.match(name):
        return check_python(args)
    if name == "git":
        return check_git(args)
    if name in DENIED_PROGRAMS or name.lower() in DENIED_PROGRAMS:
        raise Denied(f"`{name}` is not available to the issue fixer")
    if "/" in program or "\\" in program or name.endswith((".sh", ".py", ".ps1", ".bat", ".cmd", ".exe")):
        raise Denied(f"direct execution of `{program}` is not allowed (only tests via python -m unittest)")
    if name == "find" and any(a in FIND_EXEC_ARGS for a in args):
        raise Denied("find -exec/-ok/-fprint can run programs or write files; pipe to grep instead")
    if name == "sed" and any(SED_EXEC_RE.search(a) for a in args if not a.startswith("-") or a == "-e"):
        raise Denied("sed e/w commands can run programs or write arbitrary files; use the Edit tool")


def check_paths(words: list, cwd: str, conf: Confinement) -> None:
    """No argument (including redirection targets) may resolve into the main checkout or the home directory."""
    for w in words:
        for candidate in [w] + ([w.split("=", 1)[1]] if "=" in w else []):
            if candidate.startswith("~"):
                raise Denied(f"{candidate}: home-directory paths are off limits")
            if "/" not in candidate and not candidate.startswith("."):
                continue
            target = candidate if os.path.isabs(candidate) else os.path.join(cwd, candidate)
            if conf.in_main(target):
                raise Denied(f"{candidate} resolves into the main checkout, which is off limits")


def evaluate(command, conf: Confinement) -> str:
    """Returns '' when the Bash command is allowed, else the denial reason."""
    if not isinstance(command, str) or not command.strip():
        return "empty or missing command"
    for pattern, what in RAW_DENY:
        if pattern.search(command):
            return f"{what} is not allowed in the issue fixer"
    try:
        segments = split_segments(command)
        first = segments[0] if segments else []
        if len(first) != 2 or first[0] != "cd" or not os.path.isabs(first[1]) or not conf.worktree_of(first[1]):
            raise Denied("every command must start with `cd <absolute path of the issue worktree> && ...`")
        cwd = os.path.realpath(first[1])
        for seg in segments[1:]:
            if seg and seg[0] == "cd":
                if len(seg) != 2:
                    raise Denied("cd takes exactly one directory")
                target = seg[1] if os.path.isabs(seg[1]) else os.path.join(cwd, seg[1])
                if conf.in_main(target) or not conf.worktree_of(target):
                    raise Denied(f"cd {seg[1]} leaves the issue worktree")
                cwd = os.path.realpath(target)
                continue
            check_paths(seg, cwd, conf)
            check_program(seg)
    except Denied as e:
        return str(e)
    return ""


def evaluate_payload(payload: dict, conf: Confinement) -> str:
    tool = payload.get("tool_name")
    tool_input = payload.get("tool_input") or {}
    if tool == "Bash":
        return evaluate(tool_input.get("command"), conf)
    if tool in EDIT_TOOLS:
        try:
            check_edit_path(tool_input.get("file_path") or tool_input.get("notebook_path"), conf)
        except Denied as e:
            return str(e)
    return ""


def main() -> int:
    try:
        payload = json.load(sys.stdin)
    except (ValueError, OSError) as e:
        print(f"issue_fixer_guard: unreadable hook input ({e}); denied (fail closed).", file=sys.stderr)
        return 2
    if not isinstance(payload, dict):
        print("issue_fixer_guard: hook input is not an object; denied (fail closed).", file=sys.stderr)
        return 2
    if payload.get("tool_name") not in EDIT_TOOLS | {"Bash"}:
        return 0
    try:
        conf = Confinement.from_project_dir(os.environ.get("CLAUDE_PROJECT_DIR") or payload.get("cwd") or ".")
    except (Denied, OSError, subprocess.SubprocessError) as e:
        print(f"issue_fixer_guard: {e}; denied (fail closed).", file=sys.stderr)
        return 2
    reason = evaluate_payload(payload, conf)
    if reason:
        print(f"BLOCKED by issue_fixer_guard: {reason}. Work only inside the issue worktree; allowed shell: "
              "read-only tools, read-only git, python -m unittest/compileall/py_compile/pytest, tests under "
              "tests/ and scripts/dev/sync_claude_assets.py. Report anything else to the orchestrator in your "
              "final response instead of working around it.", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
